### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by teionn** [dashingsoft/pyarmor-webui#1]
I specified Pyarmor-regfile-1.zip to register Pyarmor, but an error occurred.
The zip exists at the specified path location, but Invalid argument is displayed and Pyarmor cannot be registered.

environment
- windows 10 Pro
- Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
  ('64bit', 'WindowsPE')

```bat
INFO     Call pyarmor: ['register', "'C:\\Users\\%USERNAME%/pyarmor-regfile-1.zip'"]
INFO     PyArmor Trial Version 5.9.2
INFO     Start to register keyfile: 'C:\Users\%USERNAME%\pyarmor-regfile-1.zip'
ERROR    Failed to handle request
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\pyarmor\webui\server.py", line 65, in do_POST
    result['data'] = self.root_handler.dispatch(self.path[1:], args)
  File "c:\python37\lib\site-packages\pyarmor\webui\handler.py", line 42, in dispatch
    return getattr(self, 'do_' + path)(args)
  File "c:\python37\lib\site-packages\pyarmor\webui\handler.py", line 116, in do_register
    call_pyarmor(cmd_args)
  File "c:\python37\lib\site-packages\pyarmor\webui\handler.py", line 20, in call_pyarmor
    pyarmor_main(args)
  File "c:\python37\lib\site-packages\pyarmor\pyarmor.py", line 1222, in main
    args.func(args)
  File "c:\python37\lib\site-packages\pyarmor\pyarmor.py", line 696, in _register
    register_keyfile(args.filename, legency=args.legency)
  File "c:\python37\lib\site-packages\pyarmor\utils.py", line 910, in register_keyfile
    f = ZipFile(filename, 'r')
  File "c:\python37\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: "'C:\\Users\\%USERNAME%\\pyarmor-regfile-1.zip'"
127.0.0.1 - - [09/Mar/2020 18:35:12] "POST /register HTTP/1.1" 200 -
```

**Comment by jondy** [comment]
Fix it in v0.7, please upgrade `pyarmor-webui` to the latest version.
