### ISSUE TITLE
Script packaging does not work with mode "Pack all to one file with outer license"

### ISSUE THREAD

**Issue by betepok13** [dashingsoft/pyarmor-webui#3]
I am trying to package my script into one exe file. But error appears in console:

![изображение](https://user-images.githubusercontent.com/40733196/96363588-0a193200-113e-11eb-8916-90004484de20.png)

As you can see in the screenshot, webui does not place separators in the file path.

I have the following settings:

1. 
![изображение](https://user-images.githubusercontent.com/40733196/96363773-edc9c500-113e-11eb-9748-6549fa859f97.png)
2.
![изображение](https://user-images.githubusercontent.com/40733196/96363879-8f511680-113f-11eb-845b-2aa800a0b47f.png)
3.
![изображение](https://user-images.githubusercontent.com/40733196/96363513-92e39e00-113d-11eb-9c14-1a37ad3b242c.png)
4.
![изображение](https://user-images.githubusercontent.com/40733196/96363519-9a0aac00-113d-11eb-9311-9c23ec71af55.png)

**pyarmor == 6.4.3
pyarmor-webui == 1.2.6**

And this is full log from console webui:
```
C:\Python381\python.exe C:\Python381\lib\site-packages\pyarmor\pyarmor.py build -B -O scripts\dist\obf --package-runtime 0 --with-license outer C:\Users\User\.pyarmor\projects\project-1


INFO     ==================== Run command ====================
INFO     PyArmor Version 6.4.3
INFO     Build project C:\Users\User\.pyarmor\projects\project-1 ...
INFO     Check project
INFO     Use capsule: C:\Users\User\.pyarmor\.pyarmor_capsule.zip
INFO     Output path is: scripts\dist\obf
INFO     Taget platforms: []
INFO     Update target platforms to: ['windows.x86.25.py38']
INFO     ====================================================
INFO     Reload PyArmor with platform: windows.x86.21
INFO     ====================================================
INFO     PYARMOR_PLATFORM is windows.x86.21
INFO     Generating super runtime library to scripts\dist\obf
INFO     Extract pytransform.key
INFO     Use outer license file
INFO     Copying C:\Users\User\.pyarmor\platforms\windows\x86\25\py38\pytransform.pyd
INFO     Rename extension to pytransform_vax_000781.pyd
INFO     Patch extension scripts\dist\obf\pytransform_vax_000781.pyd
INFO     Patch library file OK
INFO     Generate runtime files OK
INFO     Use protection template: ..\lib\site-packages\pyarmor\protect_code2.pt
no previously-included directories found matching 'dist\obf'
INFO     Save obfuscated scripts to "scripts\dist\obf"
INFO     Read public key from capsule
INFO     Disable increment build
INFO     Search scripts from C:\Python381\Scripts\scripts
INFO     Obfuscate scripts with mode:
INFO     Obfuscating the whole module is on
INFO     Obfuscating each function is on
INFO     Autowrap each code object mode is on
INFO     Restrict mode is 5
INFO     Advanced value is 4
INFO     Super mode is on
INFO            MyScript.py -> scripts\dist\obf\MyScript.py
INFO     Enable inline plugin
INFO     Found plugin check_ntp_time at: C:\Python381\lib\site-packages\pyarmor\plugins\check_ntp_time.py
INFO     Found plugin assert_armored at: C:\Python381\lib\site-packages\pyarmor\plugins\assert_armored.py
INFO     Patch this entry script with protection code
INFO     1 scripts has been obfuscated
INFO     Build project OK.
INFO     ==================== End command ====================

INFO     Create temp path: scripts\dist\obf\temp
INFO     Found runtime module pytransform_vax_000781.pyd
INFO     Copy scripts\dist\obf\pytransform_vax_000781.pyd to temp path
INFO     Run PyInstaller to generate .spec file...
INFO

C:\Python381\python.exe -m PyInstaller.utils.cliutils.makespec --icon C:/Python381/Scripts/scripts/icon.ico --noconsole --onefile --runtime-hook C:Python381libsite-packagespyarmorwebuidatacopy_license.py -p scripts\dist\obf\temp --hidden-import pytransform_vax_000781 --additional-hooks-dir scripts\dist\obf\temp scripts\MyScript.py


INFO     ==================== Run command ====================
wrote C:\Python381\Scripts\MyScript.spec
now run pyinstaller.py to build the executable
INFO     ==================== End command ====================

INFO     Save .spec file to MyScript.spec
INFO     Generate hook script: scripts\dist\obf\temp\hook-pytransform_vax_000781.py
INFO     Patching .spec file...
INFO     Save patched .spec file to MyScript-patched.spec
INFO     Run PyInstaller with patched .spec file...
INFO

C:\Python381\python.exe -m PyInstaller --distpath scripts\dist --icon C:/Python381/Scripts/scripts/icon.ico --noconsole --onefile --runtime-hook C:Python381libsite-packagespyarmorwebuidatacopy_license.py -y --clean MyScript-patched.spec


INFO     ==================== Run command ====================
79 INFO: PyInstaller: 4.0
79 INFO: Python: 3.8.1
80 INFO: Platform: Windows-10-10.0.16299-SP0
82 INFO: UPX is not available.
83 INFO: Removing temporary files and cleaning cache in C:\Users\User\AppData\Roaming\pyinstaller
84 INFO: Extending PYTHONPATH with paths
['C:\\Python381\\Scripts\\scripts',
 'C:\\Python381\\Scripts\\scripts\\dist\\obf\\temp',
 'C:\\Python381\\Scripts']
84 INFO: checking Analysis
99 INFO: Building Analysis because Analysis-00.toc is non existent
99 INFO: Initializing module dependency graph...
99 INFO: Caching module graph hooks...
115 INFO: Analyzing base_library.zip ...
4063 INFO: Processing pre-find module path hook distutils from 'C:\\Python381\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
4063 INFO: distutils: retargeting to non-venv dir 'C:\\Python381\\lib'
6284 INFO: Caching module dependency graph...
6416 INFO: running Analysis Analysis-00.toc
6416 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Python381\python.exe
6785 INFO: Analyzing scripts\MyScript.py
6900 INFO: Analyzing hidden import 'pytransform_vax_000781'
6900 INFO: Processing module hooks...
6900 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Python381\\lib\\site-packages\\PyInstaller\\hooks'...
6900 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Python381\\lib\\site-packages\\PyInstaller\\hooks'...
6984 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Python381\\lib\\site-packages\\PyInstaller\\hooks'...
7147 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\Python381\\lib\\site-packages\\PyInstaller\\hooks'...
7263 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Python381\\lib\\site-packages\\PyInstaller\\hooks'...
7263 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Python381\\lib\\site-packages\\PyInstaller\\hooks'...
7263 INFO: Loading module hook 'hook-xml.py' from 'C:\\Python381\\lib\\site-packages\\PyInstaller\\hooks'...
7332 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Python381\\lib\\site-packages\\PyInstaller\\hooks'...
7463 INFO: checking Tree
7463 INFO: Building Tree because Tree-00.toc is non existent
7463 INFO: Building Tree Tree-00.toc
7531 INFO: checking Tree
7531 INFO: Building Tree because Tree-01.toc is non existent
7531 INFO: Building Tree Tree-01.toc
7562 INFO: Looking for ctypes DLLs
7600 INFO: Analyzing run-time hooks ...
7600 INFO: Including custom run-time hook 'C:Python381libsite-packagespyarmorwebuidatacopy_license.py'
Traceback (most recent call last):
  File "C:\Python381\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python381\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python381\lib\site-packages\PyInstaller\__main__.py", line 121, in <module>
    run()
  File "C:\Python381\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python381\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python381\lib\site-packages\PyInstaller\building\build_main.py", line 720, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python381\lib\site-packages\PyInstaller\building\build_main.py", line 667, in build
    exec(code, spec_namespace)
  File "MyScript-patched.spec", line 6, in <module>
    a = Analysis(['scripts\\MyScript.py'],
  File "C:\Python381\lib\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
    self.__postinit__()
  File "C:\Python381\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "C:\Python381\lib\site-packages\PyInstaller\building\build_main.py", line 443, in assemble
    priority_scripts = self.graph.analyze_runtime_hooks(self.custom_runtime_hooks) + priority_scripts
  File "C:\Python381\lib\site-packages\PyInstaller\depend\analysis.py", line 675, in analyze_runtime_hooks
    rthooks_nodes.append(self.run_script(hook_file))
  File "C:\Python381\lib\site-packages\PyInstaller\depend\analysis.py", line 318, in run_script
    return super(PyiModuleGraph, self).run_script(
  File "C:\Python381\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1386, in run_script
    with open(pathname, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Python381\\Scripts\\Python381libsite-packagespyarmorwebuidatacopy_license.py'
INFO     ==================== End command ====================
```
My files in the directory:
![изображение](https://user-images.githubusercontent.com/40733196/96363802-1651bf00-113f-11eb-8245-3c5661d9e7e9.png)

If I choose this mode:
![изображение](https://user-images.githubusercontent.com/40733196/96363921-f078ea00-113f-11eb-8880-6cdc7d9ed599.png)
then everything works well. The file MyScript.exe is created.

**Comment by jondy** [comment]
Fix it in v1.2.7, please upgrade `pyarmor-webui` to latest version.
